# Generated by Django 5.1.15 on 2026-06-16 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_billing_email'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAppWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_app_id', models.CharField(max_length=255, unique=True)),
                ('external_app_slug', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_app_workspaces', to='organizations.organization')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_app_link', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'External app ↔ workspace link',
            },
        ),
    ]
